### ISSUE TITLE
how to use different optimizer for wide and deep part?

### ISSUE THREAD

**Issue by liudragonfly** [jrzaurin/Wide-and-Deep-PyTorch#1]
In the implementation of TensorFlow, wide part uses FTRL and deep  part uses AdaGrad. 
Wide part and deep part use one optimizer in your implementation. How to use different optimizer ?
Thank you.

**Comment by jrzaurin** [comment]
Hey @liudragonfly I actually never realised of this! sorry, is being months! 

I guess you found the solution, but if not. Check this:
https://discuss.pytorch.org/t/two-optimizers-for-one-model/11085

You have to pass the wide and deep parameters to the two optimisers

```
net = Model()
part_1_parameters = ...
part_2_parameters = ...
opt1 = optimizer_1(part_1_parameters)
opt2 = optimizer_2(part_2_parameters)

### train epoch
opt1.zero_grad()
opt2.zero_grad()

loss = ...
loss.backward()

opt1.step()
opt2.step()
```

basically the weights of the wide side would be `part_1_parameters` and the weights of the deep side would be `part_2_parameters`. Hope it helps, and sorry again...I have been busy :)

**Comment by jrzaurin** [comment]
I have added a function to use different optimisers for the wide and deep part. 

Is not as "pretty" as could be, but does the job for what this repo intends to be. 

Thanks for the comment and sorry it took me months to react. I did not realised 😞 .
